import { Link } from "react-router-dom";
import { ArrowUpRight, Facebook, Mail, MapPin, Phone, Youtube } from "lucide-react";
import { useSettings } from "../lib/useSchoolData";

export default function Footer() {
  const { settings } = useSettings();
  return <footer className="bg-[#173b66] text-white" style={{ fontFamily: "var(--font-inter)" }}>
    <div className="bg-[#e4a13d] px-5 py-8 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="text-[10px] font-bold tracking-[.2em] text-[#173b66]/60 uppercase">Admissions open · 2026–27</p><h2 className="mt-2 text-2xl font-semibold tracking-tight text-[#173b66]">Make room for a bigger future.</h2></div><Link to="/admissions" className="group inline-flex items-center gap-2 self-start rounded-full bg-[#173b66] px-5 py-3 text-sm font-bold text-white transition hover:bg-[#1f5a83] sm:self-auto">Apply for admission <ArrowUpRight size={15} className="transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></Link></div></div>
    <div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-12"><div className="grid gap-12 lg:grid-cols-[1.3fr_.7fr_.9fr]">
      <div><Link to="/" className="inline-flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-white/10"><img src="https://media.base44.com/images/public/user_68a720ca6a1156f1068d37b1/9fb988c1a_dis.png" alt="Daudi International School" className="h-9 w-auto" /></span><span><span className="block text-sm font-bold">Daudi International</span><span className="mt-1 block text-[9px] font-bold tracking-[.18em] text-[#f2c46e] uppercase">School · Muzaffarpur</span></span></Link><p className="mt-6 max-w-sm text-sm leading-7 text-white/55">A non-profit, English-medium school under the Daudi Welfare Trust. Quality education for every child in Muzaffarpur.</p><div className="mt-6 flex gap-2"><a href={settings.facebook_url} target="_blank" rel="noreferrer" aria-label="Facebook" className="flex h-9 w-9 items-center justify-center rounded-full border border-white/15 text-white/55 transition hover:border-[#f2c46e] hover:text-[#f2c46e]"><Facebook size={15} /></a><a href={settings.youtube_url} target="_blank" rel="noreferrer" aria-label="YouTube" className="flex h-9 w-9 items-center justify-center rounded-full border border-white/15 text-white/55 transition hover:border-[#f2c46e] hover:text-[#f2c46e]"><Youtube size={15} /></a></div></div>
      <div><p className="footer-kicker">Explore</p><div className="mt-5 grid gap-3 text-sm text-white/55"><Link to="/about" className="transition hover:text-white">About the school</Link><Link to="/academics" className="transition hover:text-white">Academics</Link><Link to="/admissions" className="transition hover:text-white">Admissions</Link><Link to="/events" className="transition hover:text-white">Life at DIS</Link><Link to="/gallery" className="transition hover:text-white">Gallery</Link><Link to="/portal" className="transition hover:text-white">School portal</Link></div></div>
      <div><p className="footer-kicker">Find us</p><address className="mt-5 not-italic text-sm leading-7 text-white/55"><p className="flex gap-2"><MapPin size={15} className="mt-1 shrink-0 text-[#f2c46e]" />Shafi Manzil, Daudi Market,<br />Motijheel, Muzaffarpur,<br />Bihar — 842001</p><a href="tel:+916212243314" className="mt-4 flex items-center gap-2 transition hover:text-white"><Phone size={15} className="text-[#f2c46e]" />+91 621 224 3314</a><a href="mailto:daudischool.muz@gmail.com" className="mt-3 flex items-center gap-2 break-all transition hover:text-white"><Mail size={15} className="shrink-0 text-[#f2c46e]" />daudischool.muz@gmail.com</a></address></div>
    </div></div>
    <div className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 px-5 py-5 text-[10px] text-white/35 sm:flex-row sm:px-8 lg:px-12"><p>© 2026 Daudi International School · Motijheel, Muzaffarpur</p><div className="flex flex-wrap gap-4"><Link to="/best-school-in-muzaffarpur" className="transition hover:text-white">Best school in Muzaffarpur</Link><Link to="/cbse-school-in-muzaffarpur" className="transition hover:text-white">CBSE school</Link><Link to="/school-near-me" className="transition hover:text-white">School near me</Link></div></div></div>
  </footer>;
}
